language: java
sudo: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - openjdk10

before_install:
  - pip install --user codecov

script:
 - mvn clean package

after_success:
  - codecov